// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcxuWipyygK_ZTJWi8oJax1AFvqzcb3tM',
    appId: '1:589043801171:web:c0b97acf04080a4c997aa6',
    messagingSenderId: '589043801171',
    projectId: 'flutter-increment-test',
    authDomain: 'flutter-increment-test.firebaseapp.com',
    storageBucket: 'flutter-increment-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNFPOFgUJHEOIKi2cqJIfouu54p-osdfY',
    appId: '1:589043801171:android:012c11771872a3e2997aa6',
    messagingSenderId: '589043801171',
    projectId: 'flutter-increment-test',
    storageBucket: 'flutter-increment-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw8sqy6UVjrtTw4i1hNnKrBZk8m5FBCCQ',
    appId: '1:589043801171:ios:486b11dea3563e8f997aa6',
    messagingSenderId: '589043801171',
    projectId: 'flutter-increment-test',
    storageBucket: 'flutter-increment-test.appspot.com',
    iosBundleId: 'com.example.testApplication4310dakp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw8sqy6UVjrtTw4i1hNnKrBZk8m5FBCCQ',
    appId: '1:589043801171:ios:e147ef7deee9da12997aa6',
    messagingSenderId: '589043801171',
    projectId: 'flutter-increment-test',
    storageBucket: 'flutter-increment-test.appspot.com',
    iosBundleId: 'com.example.testApplication4310dakp.RunnerTests',
  );
}
